# Generated by Django 5.0 on 2023-12-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('release_year', models.IntegerField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=200)),
            ],
        ),
    ]
